### ISSUE TITLE
Change the directory structure

### ISSUE THREAD

**Issue by PseudoNerd** [EnigmaVSSUT/Hacktoberfest2019#55]
Refactor the entire repository based on languages used and concept undertaken. 
Ex : 
/python/ML/linear_regression 
/C++/Data_Structures/LinkedList

**Comment by SubhamPanigrahi** [comment]
If nobody else is working on this, i am working on structuring the Repo.

**Comment by PseudoNerd** [comment]
Cool, @SubhamPanigrahi !

**Comment by msatul1305** [comment]
go ahead!

**Comment by SubhamPanigrahi** [comment]
Structured the Directory. PR sent. reference PR#115.

**Comment by msatul1305** [comment]
Done (Y)

**Comment by msatul1305** [comment]
Thanks @SubhamPanigrahi
