### ISSUE TITLE
Add yourself to the team

### ISSUE THREAD

**Issue by msatul1305** [EnigmaVSSUT/Hacktoberfest2019#8]
Use the /docs folder to add yourself in the team

**Comment by SubhamPanigrahi** [comment]
Are we supposed to add our names to the team tab of the website, Soum bhai has created?

**Comment by msatul1305** [comment]
yes definitely you should do that.

**Comment by balgopal123** [comment]
I added my name in The docs Page 
PR Ref. #180

**Comment by SubhamPanigrahi** [comment]
I added my name in The docs Page
PR Ref. #266

**Comment by msatul1305** [comment]
ok @SubhamPanigrahi

**Comment by PKSingh0017** [comment]
Added my name
My PR reference : #277
